### ISSUE TITLE
maven 中央库没有依赖

### ISSUE THREAD

**Issue by ykdsg** [alibaba/QLExpress#1]
<dependency>
  <groupId>com.taobao.util</groupId>
  <artifactId>taobao-express</artifactId>
  <version>3.0.17</version>
</dependency>
maven 中央库并没有相应的依赖，这个有计划增加吗？

**Comment by baoxingjie** [comment]
好的，之前没有做过相关的 maven 中央库发布，需要熟悉下，争取八月份完成

有相关技术问题可以加我微信 371754252

**Comment by biezhi** [comment]
@baoxingjie 嗨，你好，你们的 `maven` 中心仓库还没有发布依赖，我如何下载到最新版本呢？

**Comment by lovepoem** [comment]
我也遇到这个问题

**Comment by yujingzhou** [comment]
提供一个repository也可以呀，可惜没找到

**Comment by baoxingjie** [comment]
已经提交中央库：



<dependency>
  <groupId>com.alibaba</groupId>
  <artifactId>QLExpress</artifactId>
  <version>3.2.0</version>
</dependency>




https://github.com/alibaba/QLExpress


后续有问题可联系我微信：371754252






<~0~>


在2017年11月20 16时03分, "王爵nice"<notifications@github.com>写道:



@baoxingjie 嗨，你好，你们的 maven 中心仓库还没有发布依赖，我如何下载到最新版本呢？
