### ISSUE TITLE
在脚本里面能够得到expressRunner 的context的引用吗？

### ISSUE THREAD

**Issue by showcup** [alibaba/QLExpress#109]
```java
ExpressRunner runner = new ExpressRunner();
DefaultContext<String, Object> context = new DefaultContext<String, Object>();
context.put("a",1);
context.put("b",2);
context.put("c",3);
String express = "pirntln($context)";
Object r = runner.execute(express, context, null, true, false);
System.out.println(r);
```
上面代码假设context在引擎里有个默认的引用叫做$context，请问有这种默认的引用变量来操作ExpressRunner.execute输入的context吗？

**Comment by showcup** [comment]
@baoxingjie

**Comment by DQinYuan** [comment]
似乎没有这种引用变量，但是可以自己定义一个全局方法用于获得 context 变量，比如 "println(getFromContext('a'))"

**Comment by baoxingjie** [comment]
`        runner.addFunction("printParams", new OperatorBase(){
            @Override
            public OperateData executeInner(InstructionSetContext parent, ArraySwap list) throws Exception {
                System.out.println(parent.getParent());
                return null;
            }
        });`
