### ISSUE TITLE
数组的取值表达式有BUG（request.AAAA[0].BBBB[0]）

### ISSUE THREAD

**Issue by Gibsonnn** [alibaba/QLExpress#116]
类似这种 request.AAAA[0].BBBB[0]
程序错误，不满足语法规范，没有匹配到合适的语法,最大匹配致[0:7]

当包含两个[]关键字的时候 就有问题， 一个没问题。

**Comment by baoxingjie** [comment]
请使用最新版本 3.2.5: 
request['AAAA'][0]['BBBB'][0]


3.2.5版本[2021-8-23]
(1)支持强大的数组符号访问属性功能（List,Map,Array）：ArrayPorpertyMixTest
