### ISSUE TITLE
案例里增加自定义操作符，用于函数的时候，我的输出结果是[1,2]，不是[1，2，3]

### ISSUE THREAD

**Issue by guangquan123** [alibaba/QLExpress#117]
@Test
    public void FunctionTest() throws Exception {
        ExpressRunner runner = new ExpressRunner();
        DefaultContext<String, Object> context = new DefaultContext<String, Object>();
        runner.addFunction("join", new JoinOperator());
        Object r = runner.execute("join(1,2,3)", context, null, false, true);
        //打印结果 [1, 2]
        System.out.println(r);
    }

public class JoinOperator extends Operator {
    @Override
    public Object executeInner(Object[] list) throws Exception {

        Object opdata1 = list[0];
        Object opdata2 = list[1];
        if (opdata1 instanceof java.util.List) {
            ((java.util.List) opdata1).add(opdata2);
            return opdata1;
        } else {
            java.util.List result = new java.util.ArrayList();
            result.add(opdata1);
            result.add(opdata2);
            return result;
        }
    }
}

没想通为什么案例是返回的是[1,2,3]

**Comment by baoxingjie** [comment]
写错了，应该是返回[1, 2]

        java.util.List result = new java.util.ArrayList();
        result.add(opdata1);
        result.add(opdata2);
        return result;
