### ISSUE TITLE
大于小于比较

### ISSUE THREAD

**Issue by hiliushuo** [alibaba/QLExpress#118]
OperatorEqualsLessMore这个类的第41行可以直接return false吗：`//进行其他大小比较操作
        if (obj1 == null || obj2 == null){
            throw new QLException("空操作数无法进行数字比较操作：left = " + obj1+",right = "+ obj2);
        }`

**Comment by nkcoder** [comment]
设置`QLExpressRunStrategy.compareNullLessMoreAsFalse=true`试试

**Comment by hiliushuo** [comment]
嗯嗯，已经升级了，我关掉这个issue
