### ISSUE TITLE
表达式中是否支持 assert 方法呐？

### ISSUE THREAD

**Issue by liushengxi13689209566** [alibaba/QLExpress#124]
比如：
        testFun("mmp = [\"a\":[[\"aa1\":6661]],4:[[\"aa2\":6662]],7:[\"aa3\":6663]];" +
                "mmp.put(666,666); for(x in mmp){ assert mmp.containsKey(666); assert 666 == mmp.get(666); } " +
                " tmp = mmp.get(4); return tmp; ", env);

**Comment by baoxingjie** [comment]
可以的，可以通过addFunction实现
`        runner.addFunction("assert", new Operator() {
            @Override
            public Object executeInner(Object[] list) throws Exception {
                return null;
            }
        });

        runner.execute("exp=1+1;assert(exp==2)"......`
