### ISSUE TITLE
Documentation improvment

### ISSUE THREAD

**Issue by gleb619** [alibaba/QLExpress#129]
Please add an example of the use of the cast operator, it's not obvious how to cast objects:
a = '1';
b = (Integer.class) a ==> will raise error:
还有单词没有完成语法匹配：4[b:line=2,col=1]

Thanks in advance!

**Comment by baoxingjie** [comment]
a = 1L;
return a.class;

-->class java.lang.Long

a = (Integer)1L;
return a.class;

-->class java.lang.Integer

参照java规范，只能进行数字类型的转化 
实现原理，情况源代码： com.ql.util.express.ExpressUtil#castObject
