### ISSUE TITLE
组合对比有bug

### ISSUE THREAD

**Issue by huanghuang36** [alibaba/QLExpress#13]
例1
表达式为7<month &&month < 12 
key为month
value为9
结果为false

例2
表达式为22<month
key为month
value为100
结果为false

例3
表达式为month < 89 
key为month
value为9
结果为false

**Comment by baoxingjie** [comment]
没有你说的问题啊，麻烦确认下使用方式，有问题单独联系我。

`        ExpressRunner runner = new ExpressRunner();
        String exp = "7<month && month < 12";
        IExpressContext<String, Object> context = new DefaultContext<String, Object>();
        context.put("month",9);
        Object result = runner.execute(exp,context,null,false,true);
        System.out.println(result);
`
