### ISSUE TITLE
ExpressRunner是线程安全的吗？可以设置成单例吗？

### ISSUE THREAD

**Issue by FLMint** [alibaba/QLExpress#137]
使用ExpressRunner后压测发现CPU占用提升了很多.
请问以下三行可以设置成单例，最后两行是每个请求都带来不一样参数的那种吗？

`//相同`
`ExpressRunner runner = new ExpressRunner();`
`runner.addFunctionOfServiceMethod(xx,xx,xx,xx);`
`runner.addOperator(xx,xx);`

`//不同`
`runner.addOperatorWithAlias(xx,xx,xx);`
`runner.execute(xx,xx,xx,xx,xx);`

**Comment by FLMint** [comment]
大部分操作不是线程安全，ExpressRunner设置成单例，给一些用到的操作加锁了

**Comment by baoxingjie** [comment]
https://github.com/alibaba/QLExpress#8%E5%A2%9E%E5%BC%BA%E4%B8%8A%E4%B8%8B%E6%96%87%E5%8F%82%E6%95%B0context%E7%9B%B8%E5%85%B3%E7%9A%84api

线程安全的，最佳实践：ExpressRunner一般都应该设置为单例。
