### ISSUE TITLE
QLExpress 逻辑处理获取原子表达式序号问题

### ISSUE THREAD

**Issue by JavaPentesters** [alibaba/QLExpress#138]
Hi, tianqiao:
您好！
其中项目中使用到逻辑表达式使用到了开源的 QLExpress 规则引擎，在实际的项目中有个问题想请教下你:
也有人问过您类似的问题：
https://blog.csdn.net/express_wind/article/details/84603173?spm=1001.2014.3001.5501

例如表达式 1 && 2  (4 || 5) && (6 || 7)
要求结果除了true/false外，如果最终操作不被允许，还想得出具体不被允许的原因（哪一段不能通过）

您在博客中的回答了该问题：

1、避免逻辑短路，因为要输出所有出错信息。

设置runner属性即可，这个设置在很多场景下还是很有用的（即想运行完所有的表达式，又想获取一个最后的结果）。

runner.setShortCircuit(true);

2、友好地显示出错信息。

ExpressRunner.addOperatorWithAlias(String keyWordName, String realKeyWordName,String errorInfo)
美其名曰：“操作符 重命名”，这个函数其实是专为逻辑判断出错信息的设计的。

我遇到的问题是：
每个原子表达式可能是一个RPC函数调用，即要通过设置runner.setShortCircuit(true)实现逻辑短路减少无效的RPC调用，也想输出具体被短路的原子表达式的序号（！！注意是序号），
例如逻辑表达式 (100>99)  &&  (2>1 || 4>1) && (3>5 || 7>8)，我们可给每个原子表达式设置个编号
1 && 2 （3 || 4） && （5 || 6）
设置了逻辑短路后，只会执行 100>99（1）、2>1（3）、3>5（5） 三个表达式，

Object r = runner.execute("(100>99)  &&  (2>1 || 4>1) && (3>5 || 7>8)", expressContext, errorInfos, true, false);

其中errorInfos 可以输出被执行的原子表达式，但无法获取原子表达式的序号，看了一部分代码，感觉还是有点复杂，目前没有特别好的思路暂时关闭掉了逻辑短路，希望你能向我们提供一些详细或者指导性的意见，非常感谢！

**Comment by JavaPentesters** [comment]
@baoxingjie @gitter-badger @alibaba-oss

**Comment by JavaPentesters** [comment]
想到一种解决方案：
1、针对每个原子表达式增加一个序号
2、 原子表达式结果"$1:$2:${序号}"增加序号，唯一的缺陷是相同的运算符需要安排不同的别名

 @Test
    public void testGetRandInt() throws Exception {
        ExpressRunner runner = new ExpressRunner();
        runner.setShortCircuit(true);
        IExpressContext<String, Object> expressContext = new DefaultContext<>();
        runner.addFunctionOfServiceMethod("getRandInt", this, "getRandInt", new Class[] {}, null);

        // 默认的不定参数可以使用数组来代替
        // “操作符 重命名”，这个函数其实是专为逻辑判断出错信息的设计 runner.addOperatorWithAlias("小于","<","$1 小于 $2 不满足期望");
        List<String> errorInfo = new ArrayList<>();
        runner.addOperatorWithAlias("等于1", "==", "$1:$2:1");
        runner.addOperatorWithAlias("大于2", ">", "$1:$2:2");
        runner.addOperatorWithAlias("大于3", ">", "$1:$2:3");
        runner.addOperatorWithAlias("等于4", "==", "$1:$2:4");
        runner.addOperatorWithAlias("等于5", "==", "$1:$2:5");
        runner.addOperatorWithAlias("等于6", "==", "$1:$2:6");

        Object r = runner.execute(
            "10 等于1 10 && getRandInt() 大于2 0 && (getRandInt() 大于3 0 || getRandInt() 等于4 1) && (getRandInt() 等于5 0 || getRandInt() 等于6 1)",
            expressContext, errorInfo, true, false);
        System.out.println(r);
        System.out.println(ToStringBuilder.reflectionToString(errorInfo.toArray()));

    }

    public int getRandInt() {
        int i = new Random().nextInt(100);
        System.out.println("i:" + i);
        return i;
    }

**Comment by baoxingjie** [comment]
> 想到一种解决方案：
> 1、针对每个原子表达式增加一个序号
> 2、 原子表达式结果"$1:$2:${序号}"增加序号，唯一的缺陷是相同的运算符需要安排不同的别名
> 
> ```
>  @Test
>     public void testGetRandInt() throws Exception {
>         ExpressRunner runner = new ExpressRunner();
>         runner.setShortCircuit(true);
>         IExpressContext<String, Object> expressContext = new DefaultContext<>();
>         runner.addFunctionOfServiceMethod("getRandInt", this, "getRandInt", new Class[] {}, null);
> 
>         List<String> errorInfo = new ArrayList<>();
>         runner.addOperatorWithAlias("等于1", "==", "$1:$2:1");
>         runner.addOperatorWithAlias("大于2", ">", "$1:$2:2");
>         runner.addOperatorWithAlias("大于3", ">", "$1:$2:3");
>         runner.addOperatorWithAlias("等于4", "==", "$1:$2:4");
>         runner.addOperatorWithAlias("等于5", "==", "$1:$2:5");
>         runner.addOperatorWithAlias("等于6", "==", "$1:$2:6");
> 
>         Object r = runner.execute(
>             "10 等于1 10 && getRandInt() 大于2 0 && (getRandInt() 大于3 0 || getRandInt() 等于4 1) && (getRandInt() 等于5 0 || getRandInt() 等于6 1)",
>             expressContext, errorInfo, true, false);
>         System.out.println(r);
>         System.out.println(ToStringBuilder.reflectionToString(errorInfo.toArray()));
> 
>     }
> 
>     public int getRandInt() {
>         int i = new Random().nextInt(100);
>         System.out.println("i:" + i);
>         return i;
>     }
> ```
> 
> 输出结果格式如下：
> 
> ```
> [{ 10 : 10 :1: true, 69 : 0 :2: true, 48 : 0 :3: true, 97 : 0 :5: false, 1 : 1 :6: true}]
> ```

very good
