### ISSUE TITLE
如何获取表达式的值

### ISSUE THREAD

**Issue by javafanslz** [alibaba/QLExpress#139]
我们用 runner.getOutVarNames(exp);获取变量，如何获取变量对应的值是什么

**Comment by Riseiki** [comment]
表达式里的除逻辑运算符，关键字以外的参数列表

**Comment by baoxingjie** [comment]
> 我们用 runner.getOutVarNames(exp);获取变量，如何获取变量对应的值是什么

这个应该运行完之后，从context里面去获取。getOutVarNames是编译器直接判断出来的，不依赖实际参数运行
