### ISSUE TITLE
关于if嵌套if语句的疑问！？

### ISSUE THREAD

**Issue by xmzhujw** [alibaba/QLExpress#14]
您好，大神：
    最近在用贵公司的ql，可是发现if里面无法嵌套if语句，比如if(if 1==2 then false else true) then 1 else 2
这种语句无法执行，程序会报：程序错误，不满足语法规范。
   请问一下支持类似这种语法吗？已加您微信了，不知道您收到，谢谢大神。

**Comment by lovepoem** [comment]
建议提交一个merge request。不能解决问题的，添加一个测试用例也行

**Comment by baoxingjie** [comment]
这个语法可能是QLExpress 2.0 才支持的，QLExpress 3.0 语法进行了重新规范，更像是java的标准语法。
比如：
if (1==2) then false else true
是可以执行的，它属于一个代码块,返回 true
但是
a = (if (1==2) then false else true) 是不行的，这个和java类似
所以 if(if 1==2 then false else true) then 1 else 2  也是不支持的。

你可以写成两句：
if (1==2) then a = false else a = true;
if(a) then 1 else 2 

但我们更推荐的写法是类似java的
if (1==2) { a = false}else{a = true}
if(a){return 1}else{return 2}

新的文档可以参照github
https://github.com/alibaba/QLExpress
