### ISSUE TITLE
重写计算操作，如何加进去

### ISSUE THREAD

**Issue by lizhichao999** [alibaba/QLExpress#146]
< > <= >= 这些有些情况是没参数传进去，导致报错，想重写，但是加不进去
 runner.addOperator("<", new OperatorEqualsLessMoreExt("<"));
有什么好的方式吗

**Comment by lizhichao999** [comment]
runner.getOperatorFactory().replaceOperator("<", new OperatorEqualsLessMoreExt("<"));

**Comment by baoxingjie** [comment]
> runner.getOperatorFactory().replaceOperator("<", new OperatorEqualsLessMoreExt("<"));

这种方式应该是可以的
