### ISSUE TITLE
InstructionFactory 缓存

### ISSUE THREAD

**Issue by newbigTech** [alibaba/QLExpress#15]
InstructionFactory的Map<String,InstructionFactory> instructionFactory 只看到有get , 没看到那里有put
```
public static InstructionFactory getInstructionFactory(String factory) {
	try {
		InstructionFactory result = instructionFactory.get(factory);
		if (result == null) {
			result = (InstructionFactory) Class.forName(factory)
					.newInstance();
		}
		return result;
```

**Comment by baoxingjie** [comment]
这是一个不需要对外暴露的内部对象，请问你使用过程中遇到什么问题，或者需要做什么特殊处理吗？

**Comment by baoxingjie** [comment]
这是一个不需要对外暴露的内部对象，请问你使用过程中遇到什么问题，或者需要做什么特殊处理吗？

**Comment by newbigTech** [comment]
instructionFactory.get 每次都返回null ,Map<String,InstructionFactory> instructionFactory 的作用是什么？

**Comment by wongswoon** [comment]
我也觉得这个有问题，instructionFactory为啥没有put？map的意义是啥？
