### ISSUE TITLE
Can not run on Android Platform

### ISSUE THREAD

**Issue by AnswerZhao** [alibaba/QLExpress#151]
Thi lib dependenies some Java APIs which are removed from Android platform, such as `java/beans/PropertyDescriptor`.  So it can not run on Android. Have some plan to solve it?

**Comment by DQinYuan** [comment]
QLExpress not use PropertyDescriptor directly. Perhaps it is indirect referenced by apache commons-beanutils

**Comment by baoxingjie** [comment]
QLExpress 可适用于android，是通过解析脚本动态解析然后反射调用的。如果方法找不到需要，jvm虚拟机里可能没有注入这个jar包。请通过正常的java调用测试是否可以正常运行。
