### ISSUE TITLE
循环调用会导致方法被执行多次

### ISSUE THREAD

**Issue by wanghuizuo** [alibaba/QLExpress#154]
3.2.5版本，期望结果是
test1:1
test2:1
test1:0
test2:0
但是实际结果却是
test1:1
test2:1
test1:0
test2:0
test2:0
test2方法被多调用一次

  public class Foo {
  
      public static int test1(Integer i) throws Exception {
        System.out.println("test1:" + i);
        DefaultContext<String, Object> context = new DefaultContext<>();
        context.put("i", i);
        EXPRESS_RUNNER.execute("test2(i)", context, null, true, false);
        return 0;
      }
  
      public static int test2(Integer i) throws Exception {
        System.out.println("test2:" + i);
        if (i == 0) {
          return 0;
        }
        test1(0);
        return 0;
      }
  
      public static void main(String[] args) throws Exception {
        EXPRESS_RUNNER.addFunctionOfServiceMethod(
            "test2", new Foo(), "test2", new Class[] {Integer.class}, null);
        test1(1);
      }
    }

**Comment by DQinYuan** [comment]
test1 方法中又嵌套执行了脚本 `test2(i)`,  如果 test1 也是在脚本环境中执行的话，目前 QLExpress 是不支持脚本嵌套执行的，就会出现很奇怪的问题。test1 和 test2 反正都在同一个 Java 类里，直接调用就行了，没必再在脚本中执行
