### ISSUE TITLE
QL表达式中支持反射调用方法吗

### ISSUE THREAD

**Issue by TomousLSH** [alibaba/QLExpress#159]
ql中通过反射拿到了Method对象，可以打印出来。但是无论是公共方法还是私有方法，调用invoke都报错
Object res= destMethod.invoke(cls.newInstance(), "abc", "123");

**Comment by baoxingjie** [comment]
https://github.com/alibaba/QLExpress/blob/master/VERSIONS.md
使用3.2.6 的注解功能
