### ISSUE TITLE
为什么解析不了这种表达式呢-(0.22+7.88)，括号前加一个负号，结果为null

### ISSUE THREAD

**Issue by Hwangmingzhao** [alibaba/QLExpress#164]

**Comment by DQinYuan** [comment]
`-` 是作为中间运算符解析的，不支持作为前缀。建议写作 `0-(0.22+7.88)`

目前我们正在开发新版，计划规避之前的种种缺陷。有什么需求可以加微信聊聊，有兴趣可以把微信发我邮箱 `dqydqyuan@gmail.com`
