### ISSUE TITLE
请问怎么实例化静态内部类？

### ISSUE THREAD

**Issue by dandan67** [alibaba/QLExpress#168]
请问怎么实例化静态内部类？

**Comment by luohayiren** [comment]
比如A类的内部类B
实例化的时候这样
b = new A$B();

**Comment by dandan67** [comment]
如果要引用class文件呢？我使用A.B.class或者A$B.class都会报错

**Comment by pymBupt** [comment]
package com.ql.util.express.issue;

import com.ql.util.express.DefaultContext;
import com.ql.util.express.ExpressRunner;
import com.ql.util.express.IExpressContext;
import org.junit.Test;

public class Issue168Test {
    @Test
    public void test() throws Exception {
        ExpressRunner runner = new ExpressRunner(false, true);
        String exp = "\r\n"
            + "import com.ql.util.express.issue.Issue168Test$Issue168InnerClass;\r\n"
            + "return new Issue168Test$Issue168InnerClass();\r\n";

        IExpressContext<String, Object> context = new DefaultContext<>();
        Object result = runner.execute(exp, context, null, false, false);
        System.out.println("result = " + result);
    }

    public static class Issue168InnerClass {

    }
}

**Comment by DQinYuan** [comment]
新版本4.0考虑提升对 Java 的兼容性
