### ISSUE TITLE
使用方法时，方法参数，无法支持子类对象传入，会报找不到方法

### ISSUE THREAD

**Issue by luohayiren** [alibaba/QLExpress#170]
比如 java.util.regex.Pattern#matcher这个方法
![image](https://user-images.githubusercontent.com/13634410/147308547-3fc33592-702c-424d-bc6f-b20bd5a74f82.png)
String对象是CharSequence对象的子类
传String对象，就会报java.lang.Exception: 没有找到java.util.regex.Pattern的方法：matcher([Ljava.lang.String;)

**Comment by stonelion** [comment]
发一下具体的表达式。

**Comment by taokan** [comment]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/20024754/225771099-18b61fe2-0c90-46d7-a74f-0ab7c859a59c.png">

没有出现报错

**Comment by taokan** [comment]
请升级到最新的版本，对应的jdk8
