### ISSUE TITLE
很好奇你们的表达式解析思路灵感？

### ISSUE THREAD

**Issue by darellwu** [alibaba/QLExpress#173]
"STATEMENT:TYPE=STATEMENT,DEFINE=COMMENT|STAT_IFELSE|STAT_IF|STAT_IFELSE_JAVA|STAT_IF_JAVA|STAT_FOR|STAT_MACRO|STAT_FUNCTION|STAT_CLASS|STAT_SEMICOLON",
				"LAMBDA:TYPE=EXPRESS,DEFINE=(LAMBDA_PARAMETER_DEFINE|ID)$ARROW~$LAMBDA_BODY",
				"LAMBDA_BODY:TYPE=BLOCK,DEFINE=STAT_BLOCK|EXPRESS",
				"LAMBDA_PARAMETER_DEFINE:TYPE=STATEMENT,DEFINE=LEFT_BRACKET->CHILD_EXPRESS^$(RIGHT_BRACKET~|(ID->CONST_STRING$(,~$ID->CONST_STRING)*$RIGHT_BRACKET~))",
				"STAT_BLOCK:TYPE=BLOCK,DEFINE={->STAT_BLOCK^$STAT_LIST$}~",
				"STAT_LIST:TYPE=BLOCK,DEFINE=(STAT_BLOCK|STATEMENT)*",
				"PROGRAM:TYPE=BLOCK,DEFINE=STAT_LIST#STAT_BLOCK",

看 QLExpress 表达式解析才用上面的这种方式，你们的思路灵感来源哪里？

**Comment by darellwu** [comment]
这种解析方式相较 antr4 有啥相同点跟区别呢？

**Comment by DQinYuan** [comment]
类似于手写了一个类似 antlr 的语法推到框架，不是非常好的实践。QLExpress4 正计划将这一块优化掉
