### ISSUE TITLE
Bug: 单字母相等[creditLevel == 'A'], char处理出现问题

### ISSUE THREAD

**Issue by guliangliang** [alibaba/QLExpress#174]
String express =  "Borrower_creditLevel == 'A'";
context.put("Borrower_creditLevel","A");
Object r = runner.execute(express, context, null, true, true);
        System.out.println(r);

在版本3.2.0 是正常，都是返回true， 之后的版本 包括最新版本 都是返回false；
请确认 修复

**Comment by DQinYuan** [comment]
字符串和字符默认是不相等的，如果想要忽略差别，建议打开以下选项
ExpressRunner.setIgnoreConstChar(true)
