### ISSUE TITLE
调用方法不支持可变参数方法

### ISSUE THREAD

**Issue by kolshi** [alibaba/QLExpress#18]
方法
` public boolean containsValues(String... values) `
表达式
` xxx.containsValues(v1,v2) `
报错
`java.lang.Exception: run QlExpress Exception at line n`

**Comment by baoxingjie** [comment]
是可以支持的，但是考虑到性能和兼容性，需要设置开关 DynamicParamsUtil.supportDynamicParams = true;
详情看testcase：  com.ql.util.express.test.TestMethodParams
