### ISSUE TITLE
QL表达式中是否支持Pattern正则匹配？

### ISSUE THREAD

**Issue by fightingsz** [alibaba/QLExpress#19]
QL表达式中是否支持Pattern正则匹配？

**Comment by baoxingjie** [comment]
QL本身并没有设计Pattern正则匹配的内容，但是java支持的，QL用同样的方式调用即可，你可以可以根据需要定制自己的函数
"aaaab".matches("(a)*b")
也可以直接new java.util.regex.Pattern 对象等
