### ISSUE TITLE
String.format()执行错误

### ISSUE THREAD

**Issue by OliverLiy** [alibaba/QLExpress#192]
版本：3.2.7
脚本：format = String.format("%s+%s","1","2");
报错：没有找到java.lang.Class的方法：format(java.lang.String,java.lang.String,java.lang.String)

**Comment by stonelion** [comment]
请使用：
format = String.format("%s+%s",["1","2"]);

**Comment by DQinYuan** [comment]
QLExpress 目前不支持变长参数调用。新版本计划支持，敬请期待
