### ISSUE TITLE
in不支持单字符

### ISSUE THREAD

**Issue by EasonMoran** [alibaba/QLExpress#196]
ExpressRunner runner = new ExpressRunner();
        DefaultContext<String, Object> context = new DefaultContext<>();
        context.put("partnerId", "1");
//        String express = "partnerId in (\"a\")";
        //单字符会被当成Character的问题
        //OperatorEqualsLessMore.class executeInner方法 32行比较的是"1" 和'1'
        String express = "partnerId in ('1')";
        Object r = runner.execute(express, context, null, false, true);
        System.out.println(r);

**Comment by EasonMoran** [comment]
Operator.objectEquals(obj1, obj2)不支持"1"和'1'的比较

**Comment by taokan** [comment]
方便加个微信号吗，后续新版本发布方便联系你

**Comment by DQinYuan** [comment]
"1" 和 '1' 在 QLExpress3 中是不同的类型
左边是字符串类型，而右边是字符类型
