### ISSUE TITLE
3.2.7和3.2.0 执行结果不一致 

### ISSUE THREAD

**Issue by liuswz** [alibaba/QLExpress#197]
3.2.7 会识别字符串和数值类型， 但3.2.0不会，导致结果不一样

如：
设置
Map<String, String> feature = Maps.newHashMap();
feature.put("2848", "1");
最后执行表达式：
v2848 = feature.getOrDefault('2848', -1); if(v2848==1) { return 1; } return 1111;

在3.2.0结果是1，但3.2.7结果是1111.

想知道怎么能做到版本兼容，如设置参数的方式保证兼容

**Comment by DQinYuan** [comment]
可以给出一段测试代码看看

**Comment by DQinYuan** [comment]
该修改对应的 commit

https://github.com/alibaba/QLExpress/commit/f56d1315a76486a554ac168ed624877e577f64bb#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8

3.2.2 到 3.3.3 的升级中引入的。
目前 QLExpress 的建议采用强类型判断，字符串和数字不相等，相等的前提是类型相同

**Comment by DQinYuan** [comment]
还在深入使用 QLExpress 吗？我们可以加个微信聊聊，微信号可以发我邮箱 dqydqyuan@gmail.com
