### ISSUE TITLE
请教一下，如果我想利用QLExpress取得语法树，然后生成SQL语句，要从那里下手

### ISSUE THREAD

**Issue by aohanhe** [alibaba/QLExpress#201]
您好，我现在有一个项目使用了querydsl，现在有一个需求需要把用户输入的表达式转换为querydsl表达式。我想用QLExpress提取用户的语法树，再自己来来实现sql语句的生成。我对QLEXpress不熟悉，不知道我应用从那里下手才可以取得表达式树呢。

**Comment by zhangjunqiang** [comment]
建议直接使用antlr4
