### ISSUE TITLE
OperatorIn的疑惑

### ISSUE THREAD

**Issue by bigbigbull** [alibaba/QLExpress#206]
![image](https://user-images.githubusercontent.com/46883253/182753912-e52d8842-1c52-4947-8d29-3b80a139c2f8.png)
在第一个判断中已经判定obj一定是字符串或者数字类型，第二个判断判定了list[1]是数组或集合，第三个判断obj.equals(list[1])是不是很多余

**Comment by taokan** [comment]
嗯，如你所说确实存在不合理的逻辑，我们修改下，方便加个微信吗，后续有新版本发布可以随时沟通

**Comment by DQinYuan** [comment]
这里不能删除掉，obj 判断的是 list[0] 的类型。而这里判断的是 list[1] 的类型。

in 的语法是 a in b。这里的 a 就是 obj，而 b 是 list[1].
第一个判断的含义是 a 必须是数字或者字符串类型。
第二个判断的含义是 b 必须是 array 或者 List, 否则的话 a in b 等价与 a == b

**Comment by DQinYuan** [comment]
3 处的代码确实多余
