### ISSUE TITLE
比较表达式问题

### ISSUE THREAD

**Issue by CaoAllen** [alibaba/QLExpress#207]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/9927604/184075074-265cbb92-4e22-4db2-aae1-16018a3bac96.png">
如图，当比较数值大于等于1000，该表达式始终是true。当参数传入整型的时候没问题。

**Comment by CaoAllen** [comment]
QLExpress3.2.0
jdk11

**Comment by DQinYuan** [comment]
`context` 中应该放数字 500 而不是字符串 500，放入字符串 500 就按照字符串比较了：

```java
context.put("current_point", 500);
```
