### ISSUE TITLE
异常跳跃

### ISSUE THREAD

**Issue by tiandankanfeng** [alibaba/QLExpress#214]
在 ql里头使用一些会抛异常的 api，极少数情况报错时也想要保证后续ql代码能够继续执行，如何支持，添加操作符实现函数式编程方法调用传进去方法签名捕获异常？

**Comment by taokan** [comment]
方便加我微信吗，tkk33362，后续新版本发布随时沟通

**Comment by taokan** [comment]
是的，可以用自定义函数封装一层

**Comment by DQinYuan** [comment]
能再具体描述下吗

**Comment by tiandankanfeng** [comment]
> 能再具体描述下吗

有些api，本身调用声明就有异常，好的使用姿势是捕获异常并且在真的出现异常时保证后续流程能继续执行下去，如 `URLEncoder.encode()`

**Comment by tiandankanfeng** [comment]
后续会有新版本支持，老版本确实可以封装函数来支持下.
