### ISSUE TITLE
能否稍微给出与其他开源规则引擎的一些优缺点对比呢？

### ISSUE THREAD

**Issue by felayman** [alibaba/QLExpress#22]
如题，正在调研规则引擎中，能否稍微给出与其他开源规则引擎的一些优缺点对比呢？

**Comment by wuxinshui** [comment]
同求

**Comment by baoxingjie** [comment]
qlExpress本身只是一个脚本语言，可以被封装成规则引擎，而drools本身是个规则引擎，专注于规则的条件匹配和执行，不具备可比性。

qlExpress和groovy同属脚本语言，比较如下：
1、groovy比qlExpress更兼容java语法
相对功能复杂处理过程的大段java脚本，groovy可以直接拷贝过来运行，
而qlexpress的语法很轻量，对原始的java代码有一定的兼容性问题，一般需要把数据的类型声明全部去掉，同时不支持异常处理、for循环的集合写法 等

2、qlExpress比groovy更强调功能扩展
因为qlExpress就是诞生于阿里的电商系统，定制了很多特别的常用功能需求（宏定义，语法解析，公式计算，布尔逻辑处理，操作符函数的内置替换），可读性和功能更贴合业务需要，详细看qlExpress的扩展能力部分

3、qlExpress和groovy性能相当
qlExpress和groovy同属弱类型语法，比如a+b，可以在运行时支持字符串，数字等多种计算模式，相比fel，simpleExpress 等强类型语言性能会差一个数量级。
他们都支持编译期做了缓存功能，qlExpress转化为InstructSet，groovy转化为一个特殊的groovyclass子类
