### ISSUE TITLE
关于返回对象 java.lang.ClassCastException 的问题

### ISSUE THREAD

**Issue by suimz** [alibaba/QLExpress#227]
规则：
```java
import rules.bean.QuestionOutput;

list = new ArrayList();

item = new QuestionOutput();
output.name = "语文";
output.score = 132;
list.add(output);

return list;
```

我试图返回一个集合，但是当我在规则执行后，取结果时，出现错误：
```java
// 执行规则
Object rs = qlExpressRunner.execute(express, context);
// 取出结果
ArrayList<QuestionOutput> outputList = (ArrayList<QuestionOutput>) rs;
for (QuestionOutput item : outputList) {
    System.out.println(item);
}
```

java.lang.ClassCastException: rules.bean.QuestionOutput cannot be cast to rules.bean.QuestionOutput

想请教下可否有解决的方法

**Comment by DQinYuan** [comment]
支持返回对象，这两个对象是不是来自不同的 ClassLoader
&nbsp;


932087612
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月16日(星期五) 中午12:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [alibaba/QLExpress] 关于返回对象 java.lang.ClassCastException 的问题 (Issue #227)





 
规则：
 import rules.bean.QuestionOutput; list = new ArrayList(); item = new QuestionOutput(); output.name = "语文"; output.score = 132; list.add(output); return list;
 
我试图返回一个集合，但是当我在规则执行后，取结果时，出现错误：
 java.lang.ClassCastException: rules.bean.QuestionOutput cannot be cast to rules.bean.QuestionOutput
 
想问下是不是不支持返回对象，可否有解决的方法 @DQinYuan
