### ISSUE TITLE
能增加个精确错误定位提示吗？

### ISSUE THREAD

**Issue by shanxf** [alibaba/QLExpress#23]
目前的错误提示是这样的：java.lang.Exception: 程序错误，不满足语法规范，没有匹配到合适的语法,最大匹配致[0:2]
没有将分词结果暴露出来，具体错误提示在前端没法显示，不利于快速定位问题

**Comment by baoxingjie** [comment]
qlExpress重在实用性，很多java原生的语法，try catch ，lambda都不支持，还是要仔细阅读下文档。

目前语法编译报错这一块做的确实不是很强大，一种方法就是逐句增减，排查语法在哪一行出错；还有就是runner = new ExpressRunner(false,true)，这样是可以看得到分词结果的。

在运行期，目前是可以精确定位到哪一行出错的。

**Comment by supercoptech** [comment]
行定位确实是可以的，基本上是精确对应源码中的行，列不一定准确，我猜想是代码做了预处理。
在报错的信息中用正则表达式提取 line=(\d+),col=(\d+)
