### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by KayTin-58** [alibaba/QLExpress#236]
public static void e() throws Exception {
        ExpressRunner runner = new ExpressRunner();
        DefaultContext<String, Object> context = new DefaultContext<String, Object>();
        String a = "10.0000089";
        String b= "2";
        String c ="16";
        String d = "20";
        String e = "4";
        String f="7";
        String g="2.5";

        context.put("a",10.0000089);
        context.put("b",2);
        context.put("c",16);
        context.put("d",20);
        context.put("e",4);
        context.put("f",7);
        context.put("g",2.5);

        String express = "a+(b*c-d/e+f*g)";
        Object r = runner.execute(express, context, null, false, false);
    }这个表达式执行一万次需要38s，请问有什么优化的参数嘛

**Comment by DQinYuan** [comment]
主要的时间不是在 execute，然后在 new ExpressRunner 时初始化语法树。把 ExpressRunner 提前初始化好，execute 打开缓存开关，后面每次执行就很快，肯定是在毫秒级别的
