### ISSUE TITLE
变量值的动态获取

### ISSUE THREAD

**Issue by tiandankanfeng** [alibaba/QLExpress#238]
表达式涉及变量比较多，在表达式开启中断执行下，如何通过变量值的动态获取来去避免早期直接去获取全部的变量值，这样能节省很多不必要的变量值获取的开销

**Comment by DQinYuan** [comment]
这种是不是通过自定义函数更加合适？
或者你不用 DefaultContext，而是自己实现一个动态的 IExpressContext

**Comment by tiandankanfeng** [comment]
> 这种是不是通过自定义函数更加合适？ 或者你不用 DefaultContext，而是自己实现一个动态的 IExpressContext

lgtm
