### ISSUE TITLE
操作符==增加别名===，程序报错

### ISSUE THREAD

**Issue by hitos** [alibaba/QLExpress#241]
![image](https://user-images.githubusercontent.com/13088201/229067636-e81f81ab-a657-441f-b56c-fb0cde023029.png)

**Comment by moshu023** [comment]
我按照你这种写法写了类似的 demo，调试发现 OperatorFactory 确实成功注册了别名为“===”的“==”操作符，如下图：

**Comment by moshu023** [comment]
### 1. 背景
我按照你这种写法写了类似的 demo，调试发现 OperatorFactory 确实成功注册了别名为"==="的"=="操作符，如下图：
![image](https://user-images.githubusercontent.com/48593205/228107547-66dfb0e1-2123-4d67-b1e2-13077cba8db2.png)
### 2. 问题定位
但是在进行词法分析时，调用的WordSplit.parse()方法，它的原理是根据固定的 splitWords 数组遍历将 String 类型的原句解析成由 splitWords 构成的数组。如下图所示：
![image](https://user-images.githubusercontent.com/48593205/228108480-680b0483-e611-4cb8-a9c5-069f5fe81af0.png)
### 3. 归因 
所以由于你注册的别名"==="干扰了splitWords数组字典，因为字典里有"=="和"="分隔符，它就会把三个等号拆成"=="和"="来看。就导致最终输出的词组不正确，导致后续语法分析报错了。
### 4. 解法
所以你起的别名要避免干扰词法分析，即不要用已经存在于 splitWords 数组字典的所有分隔符组合来当你的操作符别名，这是比较快的解决方式。splitWords 数组字典我给你看一下：
![image](https://user-images.githubusercontent.com/48593205/228110822-bef1cfbb-ad9b-430f-8523-c2281a06216b.png)
### 5. 个人见解
在进行词法分析时，由于基于很多运算符作为分个条件，所以一旦若干个运算符组合在一起形成别名，就很容易形成干扰。毕竟程序解析词组时，不知道你是到底语句本身写错了还是因为自己定义的操作符别名是这样。所以这里有一个问题是在进行词法分析时，没有结合注册的 nodeTypes 数组来看，我觉得可以优化一下。但是考虑到如果没有空格，可能在别名的影响下，很容易一种原文写法会产生多种歧义，所以个人也有点疑惑这一点该如何优化，或者干脆让用户避免给程序本身带来干扰，但是这好像限制了用户的自定义操作符别名范围。

**Comment by DQinYuan** [comment]
在新的 4.0 版本中会对这个进行优化。3.x 版本暂时保持原样，自定义操作符不能和内置操作符冲突
