### ISSUE TITLE
能否支持Json格式的表达式？

### ISSUE THREAD

**Issue by vampireslove** [alibaba/QLExpress#246]
能否支持下面这种Json格式的表达式判断？

{"$and":[{"status.state":{"$eq":"running"}}]}

{"$or":[{"source":{"$eq":"weather"}},{"$and":[{"scope":{"$eq":"Service"}},{"status.state":{"$eq":"running1"}}]}]}

{"$and":[{"status.temperature":{"$gt":10,"$lt":26}},{"status.pm25":{"$lt":90}},{"status.wetness":{"$eq":89}}]}

**Comment by DQinYuan** [comment]
这个是 jsonRule 的规则格式吗？
QLExpress 是个表达式引擎，不支持直接输入 json 格式。
建议自行解析 json 并执行。可以将 QLExpress 作为其一个表达式子节点，用于实现更多功能
