### ISSUE TITLE
OperatorEqualsLessMore.java 有bug，麻烦修复一下，当比较的参数有一个为null时，应该返回false。现在却报错，修复的方案：红框的取非，就可以了

### ISSUE THREAD

**Issue by muxinLi2023** [alibaba/QLExpress#247]
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/127938049/225262055-8f5b9e14-45fb-4d7d-9b01-b3f724f3a33d.png">

**Comment by pymBupt** [comment]
如果有null时，期望返回false，请设置如下参数，下述参数的默认值为false
```java
QLExpressRunStrategy.setCompareNullLessMoreAsFalse(true);
```

**Comment by muxinLi2023** [comment]
好的，感谢，我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bingo ***@***.***&gt;
发送时间: 2023年3月31日 17:42
收件人: alibaba/QLExpress ***@***.***&gt;
抄送: muxinLi2023 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/QLExpress] OperatorEqualsLessMore.java 有bug，麻烦修复一下，当比较的参数有一个为null时，应该返回false。现在却报错，修复的方案：红框的取非，就可以了 (Issue #247)





 
Closed #247 as completed.

**Comment by muxinLi2023** [comment]
你好，我想请问一下，QLExpress 如何实现expression 表达式语法检查，现在的异常信息不够明确，有更好的检查语法错误的方法或者工具吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/QLExpress"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/QLExpress] OperatorEqualsLessMore.java 有bug，麻烦修复一下，当比较的参数有一个为null时，应该返回false。现在却报错，修复的方案：红框的取非，就可以了 (Issue #247)





 
如果有null时，期望返回false，请设置如下参数，下述参数的默认值为false
 QLExpressRunStrategy.setCompareNullLessMoreAsFalse(true);
