### ISSUE TITLE
请问支持lambda表达式和匿名函数吗? 

### ISSUE THREAD

**Issue by zhouxianjun** [alibaba/QLExpress#25]
return data.stream().filter(d -> d.getKey().equals("code") && Integer.parseInt(d.getValue()) > 200).count();
OR
return data.stream().filter(new Predicate<TabMonitorData>() {
                @Override
                public boolean test(TabMonitorData tabMonitorData) {
                    return tabMonitorData.getKey().equals("code") && Integer.parseInt(tabMonitorData.getValue()) > 200;
                }
            }).count();

**Comment by baoxingjie** [comment]
qlexpress脚本侧重脚本的可读性，实用性，目前不支持try catch ，注解，lambda 等复杂的语法。
