### ISSUE TITLE
获取执行路径以及路径中的计算结果

### ISSUE THREAD

**Issue by c-s-t-z** [alibaba/QLExpress#250]
如果需要获取到执行路径,有什么方案可以获取到.类似isTrace输出的日志,但是这个配置只是输出了日志,需求上可能需要知道实际的执行路径做一些展示上公式展示上的优化.有什么方法可以得到公式(表达式)的实际(因为参数每次可能不一致导致公式所走的分支有可能不一样)执行路径么?
if paramA == "a1" or paramB == "b1" 
  then paramC
else if paramC == "c1"
   then {
     if paramA == "a1" or paramB == "b1"
        then "abc"
     else "other"
    }
else "ab"

当 paramA = "1" paramB = "1" paramC = "c1"
想得到执行路径是
1 if paramA == "a1" or paramB == "b1" (false)

2 else if paramC == "c1"(true)

3 if paramA == "a1" or paramB == "b1"(false)

4 else "other"

**Comment by DQinYuan** [comment]
不太能行。这个需求建议采用结构化的规则，而不是一个表达式
