### ISSUE TITLE
null+null

### ISSUE THREAD

**Issue by aodecv** [alibaba/QLExpress#257]
在执行这个例子：
express = "如果 (语文 + 数学 + 英语 > 270) 则 {return 1;} 否则 {return 0;}";

发现
if(null > 270) 会报错
if(null+null >270) 不等式成立

**Comment by taokan** [comment]
if(null > 270) null对象不允许和数值进行比较
if(null+null >270) null+null默认是字符串处理，="nullnull"，转换成字符串支持大小比较
有什么问题可以加我们微信tkk33362
