### ISSUE TITLE
字符串拼接 无法使用 \ 进行拼接吗

### ISSUE THREAD

**Issue by ZwzYJ999** [alibaba/QLExpress#260]
![image](https://github.com/alibaba/QLExpress/assets/83064998/cb8979be-4cd4-4ee5-82b8-6c1d08d82635)

**Comment by taokan** [comment]
支持的，你可以参考下这个case

**Comment by DQinYuan** [comment]
issue 中的表达式相当于 qlexpress 中的（因为Java会将 `\\` 转义成 `\`）：

```
"abc" + "\" + "cde"
```

第三个双引被转义，导致最后一个 `"` 没有封闭。符合预期。
