### ISSUE TITLE
使用java stream 如果集合属性是一个jsonObject，在使用put方法时 报错

### ISSUE THREAD

**Issue by jiafeijiang** [alibaba/QLExpress#261]
![image](https://github.com/alibaba/QLExpress/assets/23660022/0d23ea2e-6da1-46f5-89cd-75d4b1c697ed)

**Comment by DQinYuan** [comment]
<img width="708" alt="image" src="https://github.com/alibaba/QLExpress/assets/23725000/f46aa2ed-7fba-4f6b-9a8d-1a20d15c04cd">

这一块改成逗号即可。
