### ISSUE TITLE
脚本中定义function时, function中的变量不是局部变量

### ISSUE THREAD

**Issue by wyfsnr** [alibaba/QLExpress#263]
function test() {
    c = 4;
}
c = 2;
test();
return c;
如上脚本, 期望返回值为 2 , 实际返回为4. 这种有解决方案吗?

**Comment by DQinYuan** [comment]
QLExpress 中不写类型声明的变量都是全局变量，建议写法：

```
function test() {
    int c = 4;
}
c = 2;
test();
return c;
```
