### ISSUE TITLE
【咨询】请问有完整的语法bnf吗？

### ISSUE THREAD

**Issue by xwinie** [alibaba/QLExpress#274]

**Comment by Coder-XiaoYi** [comment]
我也在找

**Comment by DQinYuan** [comment]
https://github.com/alibaba/QLExpress/blob/master/src/main/java/com/ql/util/express/parse/KeyWordDefine4Java.java

参考这个文件，但是不是用的 bnf。是用一种自定义的语法描述的，新版本的话会迁移到 g4 上面
