### ISSUE TITLE
短路计算有Bug

### ISSUE THREAD

**Issue by ikebo** [alibaba/QLExpress#277]
期望的效果是：A && B && C，这个表达式，当我计算出A的值时，带入计算表达式，如果有正常结果，说明短路成功不需要再计算B的值，当抛出异常时（只有A的值没有B和C的值），说明需要继续计算B的值。

但是在测试的时候，A为true，B和C不传，代入计算时，表达式的值竟然是false，且没有任何报错信息。

参考短路计算的测试用例发现，A > 10 && B < 5 这种数值大小比较时是OK的，可以成功短路，但是 A && B && C时 或者 A > 10 && B时是不行的。 这应该是个Bug，麻烦看一下。

``` java
ExpressRunner runner = new ExpressRunner(true, true);
runner.setShortCircuit(true);

// qlExpress的短路计算有问题, A > 10 & B > 12 这种OK，但是 A && B这种就有问题提, 并不会报错..
String expr = "A > 90 && B == true";
// String expr = "A > 1 && B && C";
// // String[] vars = runner.getOutVarNames(expr);
IExpressContext<String, Object> context = new DefaultContext<>();
context.put("A", 100);
// // context.put("B", true);
// // context.put("C", true);
List<String> errList = new ArrayList<>();

Object iresult = runner.execute(expr, context, errList, false, false, null);
log.info("result: {}, err: {}", iresult, errList);
```

**Comment by DQinYuan** [comment]
<img width="538" alt="image" src="https://github.com/alibaba/QLExpress/assets/23725000/76aa288d-1083-4181-b03c-c8b33280eaaf">

QLExpress 短路运算中 null 默认是 false
