### ISSUE TITLE
默认的in 操作符有BUG，返回不满足期望

### ISSUE THREAD

**Issue by yushukk** [alibaba/QLExpress#282]
@Test
    public void testQlExpress() throws Exception {
        ExpressRunner runner = new ExpressRunner();
        DefaultContext<String, Object> context = new DefaultContext<String, Object>();
        context.put("a", "1");
        String express = "a in ('1','2')";
        Object r = runner.execute(express, context, null, true, false);
        //期望是true，但返回的是false
        Assert.assertFalse((Boolean)r);
    }

**Comment by yushukk** [comment]
version 3.3.1

**Comment by sxshunrj** [comment]
String express = "a in ('1','2')"，单引号包围的会被认为是java.lang.Character类型，而context里的1被认为是java.lang.String类型，这种情况下会调用object的equals方法，就会返回false了。
如果期望返回true，需要将表达式里的数字用双引号包围，例如：String express = "a in (\"1\"',\"2\")";

**Comment by DQinYuan** [comment]
com.ql.util.express.ExpressRunner#setIgnoreConstChar

开启这个选项，单引号就是 string 了
