### ISSUE TITLE
QLExpress 3.3.2 黑白名单绕过 Blacklist and whitelist bypass

### ISSUE THREAD

**Issue by L1aovo** [alibaba/QLExpress#295]
The content of this issue has been deleted due to RCTF2024

**Comment by DQinYuan** [comment]
其实 QLExpress 更多是给公司内部的运营系统配置, 也就是可信的人来配置的, 不是用来对公司外部执行脚步的, 所以安全性之前没有做的这么强.

黑名单只是为了兼容历史而存在的, 不保证安全.
白名单构造函数上确实存在问题, 我们修复下.
对外部输入的脚本还是建议用沙箱模式, 纯当个表达式语言用.

**Comment by fa1c0n1** [comment]
看具体怎么配吧，遇到的除了运行时校验，还会加上编译器白名单 QLExpressRunStrategy.setCompileWhiteCheckerList(new ArrayList<>());
