### ISSUE TITLE
升级3.3.1版本后，打了很多System.out.printl

### ISSUE THREAD

**Issue by oudezhi** [alibaba/QLExpress#296]
之前一直用的是3.3.0版本，会根据log4j级别进行日志打印如下图
![企业微信截图_1695828424956(1)](https://github.com/alibaba/QLExpress/assets/7876504/0975fe33-85f5-44a0-b1a8-3c9e390acb4a)

升级成3.3.1 版本后，直接变成了System.out.println了，用这个打日志不太规范吧？
![企业微信截图_16958283455227(1)](https://github.com/alibaba/QLExpress/assets/7876504/2e2fe4d4-1ad8-424f-b695-704093041392)

**Comment by oudezhi** [comment]
com.ql.util.express.parse.ExpressParse 这个类

**Comment by DQinYuan** [comment]
3.3.1 接触了对 logger 的以来, 这个 println 仅仅用于 QLExpress 本身的开发调试之用, 线上不建议打开 trace 开关.

如果有什么更好的建议也欢迎提 PR. 感兴趣的话可以加个微信 15295661201
