### ISSUE TITLE
设置"||"的别名为OR 的时候添加不成功提示已存在相同操作符，但是执行的时候又提示操作符不正确

### ISSUE THREAD

**Issue by moyispace** [alibaba/QLExpress#298]
![image](https://github.com/alibaba/QLExpress/assets/31463603/ced82f00-d0e3-4cef-b0c8-9e0c0e808549)
![image](https://github.com/alibaba/QLExpress/assets/31463603/15d8a723-66b3-4ed2-aeed-5cfe1dc62cdb)

**Comment by DQinYuan** [comment]
我用以下代码测试是正常的, 版本是 3.3.2
请给出你无法正常运行的代码

```java
        String express = "1==1 or 2==3";
        ExpressRunner runner = new ExpressRunner(false, true);
        Object res = runner.execute(express, new DefaultContext<>(), null, true, true);
        System.out.println(res);
```

**Comment by moyispace** [comment]
ExpressRunner runner = new ExpressRunner();
DefaultContext<String, Object&gt; userExpressContext = new DefaultContext<String, Object&gt;();
runner.addOperatorWithAlias("OR", "||", null);
String expression = "1==1 OR 2==3";
//执行表达式
Object execute = runner.execute(expression, userExpressContext, null, false, true);

&nbsp;


milo
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月26日(星期天) 晚上9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/QLExpress] 设置&quot;||&quot;的别名为OR 的时候添加不成功提示已存在相同操作符，但是执行的时候又提示操作符不正确 (Issue #298)





 
我用以下代码测试是正常的, 版本是 3.3.2
 请给出你无法正常运行的代码
         String express = "1==1 or 2==3";         ExpressRunner runner = new ExpressRunner(false, true);         Object res = runner.execute(express, new DefaultContext<&gt;(), null, true, true);         System.out.println(res);
