### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by w1014804721** [alibaba/QLExpress#30]

**Comment by w1014804721** [comment]
ExpressRunner runner = new ExpressRunner();
IExpressContext<String, Object> context = new DefaultContext<String, Object>();
String script = "\"\\\".equals(\"4\");";
Object result = runner.execute(script, context, null, true, false);
System.out.println(result);
这一段代码会报字符串没有关闭的错误，原因是在解析表达式的时候，对反斜杠的处理有误。
com.ql.util.express.parse.WordSplit中的parse方法，在找到一个引号的时候，需要找到与之配对的另一个引号，找到另一个引号之后，会判断前面是否是反斜杠，如果是反斜杠，就认为该引号被转义。这个地方应该是个bug，因为引号前面的反斜杠不一定是转义引号用的，应当改成判断该引号前面有多少个反斜杠，如果是偶数个，就说明这个引号就是结束引号，如果是奇数个，就说明是转义的引号。

**Comment by baoxingjie** [comment]
确实是个bug，我关注下

**Comment by lovejiegirl** [comment]
script = StringEscapeUtils.unescapeJava(script);
通过org.apache.commons.lang.StringEscapeUtils反转义一下就好了

**Comment by DQinYuan** [comment]
`String script = "\"\\\".equals(\"4\");";` 这个对应的 ql 代码是 `"\".equals("4");`, 这个代码就算放在 java 里也是含有不封闭字符串的。ql 里的逻辑我认为没有问题

**Comment by w1014804721** [comment]
> `String script = "\"\\\".equals(\"4\");";` 这个对应的 ql 代码是 `"\".equals("4");`, 这个代码就算放在 java 里也是含有不封闭字符串的。ql 里的逻辑我认为没有问题

String script = "\"\\\\\".equals(\"4\");";  这样也是一样的，对应的ql代码是"\\".equals("4")，
代码如下：
String script = "\"\\\\\".equals(\"4\");";
        System.out.println(script);
        System.out.println("\\".equals("4"));
        ExpressRunner runner = new ExpressRunner();
        IExpressContext<String, Object> context = new DefaultContext<String, Object>();
        Object result = runner.execute(script, context, null, true, false);
        System.out.println(result);
抛异常Exception in thread "main" java.lang.Exception: 字符串没有关闭

**Comment by wenzhuozou** [comment]
> 

这个问题可以解决么?

**Comment by wenzhuozou** [comment]
> script = StringEscapeUtils.unescapeJava(script); 通过org.apache.commons.lang.StringEscapeUtils反转义一下就好了

反转义会把所有的\都去掉，如果想保留部分\就不行了
