### ISSUE TITLE
想了解下4.0版本

### ISSUE THREAD

**Issue by lancer2** [alibaba/QLExpress#300]
之前也读了一些3.x的源码,感觉跟目前4.0的变化非常大,分支提交的也很活跃,大佬能分享下4.0的一些近况吗?  比如重构的重点是啥?  预计何时能release?
@DQinYuan

**Comment by DQinYuan** [comment]
重点是语法现代化和错误提示。
计划是最晚能到年初有一个公开的 beta 版本。
有兴趣可以加微信交流，15295661201

**Comment by lancer2** [comment]
了解,开源不易,辛苦啦
