### ISSUE TITLE
自定义不定参数函数基本类型不支持

### ISSUE THREAD

**Issue by samliu008** [alibaba/QLExpress#305]
定义一个sum不定参数，int类型；如下写法报错。必须要写Object？
是否能写确定的变量类型比如int,long,double等？
![image](https://github.com/alibaba/QLExpress/assets/69573605/dbd15cb7-933f-4fd7-a892-18b41b2d4973)

**Comment by DQinYuan** [comment]
在脚本运行时数字都是包装类型，用 Integer，而不是 int

**Comment by DQinYuan** [comment]
另外自定义函数，建议用 Number 去接数字入参，更加通用
