### ISSUE TITLE
3.2.0 异常时响应非常慢

### ISSUE THREAD

**Issue by bestpayAmes** [alibaba/QLExpress#309]
样例代码如下
```
Map map=new HashMap();
        map.put("status","N");
        ExpressRunner expressRunner = new ExpressRunner(true,false);
        DefaultContext<String, Object> context = new DefaultContext<String, Object>();
        context.putAll(map);
        Object o = expressRunner.execute("status%9", context, null, true, false);
        System.out.println(o);
```
QL版本：3.2.0
执行时间15秒

**Comment by bestpayAmes** [comment]
上面的代码15秒才跑完

**Comment by DQinYuan** [comment]
看着不太可能，有计时代码吗？

**Comment by bestpayAmes** [comment]
> 看着不太可能，有计时代码吗？

  ExpressRunner expressRunner = new ExpressRunner(true,false);
        long begin=System.currentTimeMillis();
        try{
            Map map=new HashMap();
            map.put("status","N");
            DefaultContext<String, Object> context = new DefaultContext<String, Object>();
            context.putAll(map);
            Object o = expressRunner.execute("status%9", context, null, true, false);
            System.out.println(o);
        }catch (Exception e){
            //throw e;
        }finally {
            System.out.println(System.currentTimeMillis()-begin);
        } 
有的

**Comment by DQinYuan** [comment]
```java
public class PerformanceTest {

    @Test
    public void perfTest() throws Exception {
        ExpressRunner expressRunner = new ExpressRunner(true,false);
        long begin=System.currentTimeMillis();
        try{
            Map map=new HashMap();
            map.put("status",10);
            DefaultContext<String, Object> context = new DefaultContext<String, Object>();
            context.putAll(map);
            Object o = expressRunner.execute("status%9", context, null, true, false);
            System.out.println(o);
        } finally {
            System.out.println(System.currentTimeMillis()-begin);
        }
    }
}
```

@bestpayAmes  我在自己机器上用单元测试测的, 7 ms

**Comment by bestpayAmes** [comment]
> ```java
>             map.put("status",10);
> ```

            map.put("status","N");改成非数字就能复现；

**Comment by DQinYuan** [comment]
@bestpayAmes  依旧是 9ms

![image](https://github.com/alibaba/QLExpress/assets/23725000/913641cc-26df-47a5-884f-82119863c3ec)
