### ISSUE TITLE
多线程并发的时候命中缓存场景

### ISSUE THREAD

**Issue by ruizhou8888** [alibaba/QLExpress#317]
实际场景是业务有多个规则组合 比如 [A,B,C] [B,C] [AB] ......
有很多种组合，目前通过多线程并发去计算每个组合，但是测试下来发现并没有起到作用，想问下是否因为多线程之间在争夺缓存锁导致？有其他优化方式吗？
![image](https://github.com/alibaba/QLExpress/assets/8612467/6fcdb13b-1590-4f35-ac8d-2a5c99f3bfb7)

**Comment by DQinYuan** [comment]
有单元测试吗？
如果没有预热过的话，对于同一个表达式 A，预热是单线程的。
但是执行是多线程的。
如果提前预热的好的话，应该可以提升性能。
