### ISSUE TITLE
在3.2.3引入了不兼容的修改，不支持弱类型比较。

### ISSUE THREAD

**Issue by vampireslove** [alibaba/QLExpress#325]
建议在高版本增加一个环境变量，来设置执行器使用强类型比较还是弱类型比较。否则在需要对弱类型比较需求时，将无法使用最新版本了。

**Comment by taokan** [comment]
具体影响你处理的弱类型比较case有吗

**Comment by DQinYuan** [comment]
https://github.com/alibaba/QLExpress/blob/master/VERSIONS.md

这里有不兼容的版本更新说明
