### ISSUE TITLE
使用Antlr4替换语法解析

### ISSUE THREAD

**Issue by derecknowayback** [alibaba/QLExpress#327]
有考虑使用过Antlr4做语法解析吗？当前的语法解析似乎都是手动解析字符串，开发者/使用者学习语法需要查看源码，学习成本比较高且手工解析不好迭代维护。如果有Antlr4，能有一个可靠的语法解析，对于用户友好。

**Comment by derecknowayback** [comment]
cc @DQinYuan @pymBupt

**Comment by DQinYuan** [comment]
看一下 branch_version_4.0.0.dev 分支。4.0 已经计划采用 Antlr 4 进行解析
