### ISSUE TITLE
addFunctionOfServiceMethod等方法有办法支持类似"方法重载"机制吗

### ISSUE THREAD

**Issue by nekoozero** [alibaba/QLExpress#338]
# 环境

jdk 8
ql   3.3.3   

# 代码
<img width="575" alt="image" src="https://github.com/user-attachments/assets/c0f7d0a2-2522-4378-b7be-48f76f2f6435">

```java
CustomService nekoo = new CustomService("nekoo");
expressRunner.addFunctionOfServiceMethod("h1.sayHello", nekoo, "sayHello", new Class[]{String.class}, null);
expressRunner.addFunctionOfServiceMethod("h1.sayHello", nekoo, "sayHello", new Class[]{}, null);
```

报错：
<img width="1293" alt="image" src="https://github.com/user-attachments/assets/2d34b302-8d4a-427b-a5cd-d586beb10a1d">

**Comment by jackie-coming** [comment]
> ```java
> addFunctionOfServiceMethod
> ```
![image](https://github.com/user-attachments/assets/6c0de1b4-23d7-42c1-9dd3-4dc0dbd9bb19)
参考这个test，name换一下就可以了，例如"h1.sayHello"、"h1.sayHelloString"

**Comment by jackie-coming** [comment]
> > ```java
> > addFunctionOfServiceMethod
> > ```
> 
> ![image](https://private-user-images.githubusercontent.com/64013698/357261429-6c0de1b4-23d7-42c1-9dd3-4dc0dbd9bb19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTgzNzksIm5iZiI6MTcyMzUxODA3OSwicGF0aCI6Ii82NDAxMzY5OC8zNTcyNjE0MjktNmMwZGUxYjQtMjNkNy00MmMxLTlkZDMtNGRjMGRiZDliYjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDAzMDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMjliOTBmYWJmZTgxOGE5ZjViMzU3OWNlYTdhOTU1YzAwOGI4NmQ5NDIxODMxYzAwNTNmZDE3YjFkZDBhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7RAZWFnfjd4ljkdhGw58Cu52KzKK2-wJnho2z9e_mlc) 参考这个test，name换一下就可以了，例如"h1.sayHello"、"h1.sayHelloString"

![image](https://github.com/user-attachments/assets/906d360b-146e-4069-89f0-00d7e72cdae1)
底层是通过name来判断 重复的

**Comment by nekoozero** [comment]
> > > ```java
> > > addFunctionOfServiceMethod
> > > ```
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/64013698/357261429-6c0de1b4-23d7-42c1-9dd3-4dc0dbd9bb19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTgzNzksIm5iZiI6MTcyMzUxODA3OSwicGF0aCI6Ii82NDAxMzY5OC8zNTcyNjE0MjktNmMwZGUxYjQtMjNkNy00MmMxLTlkZDMtNGRjMGRiZDliYjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDAzMDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMjliOTBmYWJmZTgxOGE5ZjViMzU3OWNlYTdhOTU1YzAwOGI4NmQ5NDIxODMxYzAwNTNmZDE3YjFkZDBhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7RAZWFnfjd4ljkdhGw58Cu52KzKK2-wJnho2z9e_mlc) 参考这个test，name换一下就可以了，例如"h1.sayHello"、"h1.sayHelloString"
> 
> ![image](https://private-user-images.githubusercontent.com/64013698/357261692-906d360b-146e-4069-89f0-00d7e72cdae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mjc5NDIsIm5iZiI6MTcyMzUyNzY0MiwicGF0aCI6Ii82NDAxMzY5OC8zNTcyNjE2OTItOTA2ZDM2MGItMTQ2ZS00MDY5LTg5ZjAtMDBkN2U3MmNkYWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA1NDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YjNkNTA5YzE3YmIyZjNmZWMxMzI5MGFiODA1NGE4MWE0ZGJjMGE1YTFmM2FhZmRmNzY0OTVhMDE0NzYwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ckBIa1yj7KDJlX-TqOGl-GjoocKfHcJX5LrlviDOUo) 底层是通过name来判断 重复的

嗯。看到了 目前这个方法应该是实现不了了 最后通过和spring整合的方式来实现的 https://github.com/alibaba/QLExpress/blob/master/src/test/java/com/ql/util/express/test/spring/SpringDemoTest.java 将重载的方法都放到了spring的同一个Bean中去了
