### ISSUE TITLE
为何给运算符取别名或者添加运算符还是报错

### ISSUE THREAD

**Issue by knight-xiaolu2023** [alibaba/QLExpress#339]
![image](https://github.com/user-attachments/assets/b1b9f9b0-19ce-4508-bab0-e4ad062432c4)
![image](https://github.com/user-attachments/assets/e1058273-f999-4204-b2e5-7dbd20744cb2)

**Comment by moyispace** [comment]
符号和值空开试试呢

**Comment by jackie-coming** [comment]
> ![image](https://private-user-images.githubusercontent.com/131353676/355659234-b1b9f9b0-19ce-4508-bab0-e4ad062432c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTQzNzEsIm5iZiI6MTcyMzUxNDA3MSwicGF0aCI6Ii8xMzEzNTM2NzYvMzU1NjU5MjM0LWIxYjlmOWIwLTE5Y2UtNDUwOC1iYWIwLWU0YWQwNjI0MzJjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwMTU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGUzMWU1NTdkZTYxNzlkMTUxYjQ1MjU1YTVkM2IxMDY4NTY4N2VhMDQzM2RiZjZmNzkxYTZmYjlmYTVjMDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0SrFU3iahHAPX76p4pw8zUVJw5x_Ial-ni5T2zdVpfE) ![image](https://private-user-images.githubusercontent.com/131353676/355659316-e1058273-f999-4204-b2e5-7dbd20744cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTQzNzEsIm5iZiI6MTcyMzUxNDA3MSwicGF0aCI6Ii8xMzEzNTM2NzYvMzU1NjU5MzE2LWUxMDU4MjczLWY5OTktNDIwNC1iMmU1LTdkYmQyMDc0NGNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwMTU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTNiOGNjZjVhZjRmZmYzNzQ3YmQ3NTdhYjI1Njc1Y2JmMTI5NzFhMjY0NDZiY2M2ZDI4MzQzMTZkNDUyZjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DTNl6Okm3HwoXq2hwLKbuaCIJ2bUrlET8q9R8XsrPkg)

基于v3.3.3版本，貌似内置的operator不需要空格也能跑。自定义的operator需要空格
![image](https://github.com/user-attachments/assets/bee8e09a-2d86-437b-bf5b-adc8facd76c1)
![image](https://github.com/user-attachments/assets/397e67bd-e823-402b-b07f-8406095afa1a)

**Comment by knight-xiaolu2023** [comment]
需要加空格，这项目这么多人用没人发现这种问题么。。怎么感觉没经过测试一样，，

**Comment by DQinYuan** [comment]
@knight-xiaolu2023  麻烦了解下编译原理，内置操作符不需要加空格，是因为 * / + - 是停用词，词法分析遇到这些停用词是会停止的，而 ➗ 或者 join 并不是停用词，也就是说他们可以是变量名的一部分，比如 ajoinb 就是合法的变量名，如果把他们作为停用词，会导致其他解析错误，所以需要空格。

其他语言让你定义 join 操作符的时候，也不可能不加空格就能跑的。
