### ISSUE TITLE
是否支持操作符< <= > >=当 对象为空的时候返回false

### ISSUE THREAD

**Issue by walh1314** [alibaba/QLExpress#34]
OperatorEqualsLessMore 类 
if (obj1 == null && obj2 == null) {
			if (opStr.equals("==")) {
				return true;
			} else if (opStr.equals("!=") || opStr.equals("<>")) {
				return false;
			} else {
				throw new Exception("两个空操作数不能执行这个操作：" + opStr);
			}
		} else if (obj1 == null || obj2 == null) {
			if (opStr.equals("==")) {
				return false;
			} else if (opStr.equals("!=") || opStr.equals("<>")) {
				return true;
			} else {
				throw new Exception("空操作数不能执行这个操作：" + opStr);
			}
		}

**Comment by baoxingjie** [comment]
新版本将会提供这种运行策略！

**Comment by baoxingjie** [comment]
新版本3.2.2 已经 提供这种运行策略 
com.ql.util.express.config.QLExpressRunStrategy.setAvoidNullPointer(true)

**Comment by zengjianfei** [comment]
com.ql.util.express.config.QLExpressRunStrategy.setAvoidNullPointer(true) 这种策略不能处理 null < 10  着这样的情况不知道还有其它处理方法没有
