### ISSUE TITLE
问个问题，请问能调用java的泛型方法么？

### ISSUE THREAD

**Issue by bigfacewo** [alibaba/QLExpress#36]
如题

**Comment by baoxingjie** [comment]
java的泛型方法 其实只是编译期给语法检查优化，实际在运行期并不影响。

https://github.com/alibaba/QLExpress/#%E5%92%8Cjava%E8%AF%AD%E6%B3%95%E7%9B%B8%E6%AF%94%E8%A6%81%E9%81%BF%E5%85%8D%E7%9A%84%E4%B8%80%E4%BA%9Bql%E5%86%99%E6%B3%95%E9%94%99%E8%AF%AF
