### ISSUE TITLE
我通过macro调用function,报找不到function

### ISSUE THREAD

**Issue by qianzhiheilv** [alibaba/QLExpress#4]
```
 ExpressRunner runner = new ExpressRunner(false, false);
          runner.addFunctionOfServiceMethod("changeBrand",new BrandService(),"changeBrand",new Class[] {DroolsRequest.class},null);
             runner.addMacro("changeBrandMacro","changeBrand11(droolsRequest)");
            DefaultContext<String, Object> context = new DefaultContext<>();
            context.put("PARAM1", 12);
            context.put("PARAM2", 60);
            context.put("droolsRequest",droolsRequest);
            expression = initial(runner, “changeBrandMacro and PARAM1 + PARAM2>60”);
            result = (Boolean) runner.execute(expression, context, errorInfo, true, false);
```
其中
```
public class BrandService {

    public boolean changeBrand(DroolsRequest droolsRequest){
        System.out.println("++++++++++++++++++++++++++++++++++++++++++++++");
        System.out.println(droolsRequest.asXML());
        return true;
    }
}
```
报错
java.lang.Exception: 在Runner的操作符定义和自定义函数中都没有找到"changeBrand"的定义
我看了下源码，macro中去调用function时候，查找的function是去symbolTable找的，但是addFunctionOfServiceMethod却是往functions里边添加的，请问是我什么地方写错了么？

**Comment by qianzhiheilv** [comment]
我知道原因了。。。addFunctionOfServiceMethod必须放在addMacro前面。。要么调用不到。。我原来写反过来的。。

**Comment by zhihuchenl** [comment]
String sum = "function sum(int a,int b){\n" +
                "  return a+b;\n" +
                "};\n";

        runner.addMacro("bbb", sum);
        runner.addFunctionOfServiceMethod("add", new BindObjectMethod(), "add",
                new Class[] { Integer.class, Integer.class }, null);

        DefaultContext<String, Object> context = new DefaultContext<String, Object>();

        String express = "add(1,2);bbb;sum(1,22)";
        Object r = runner.execute(express, context, null, true, false);
        System.out.println(r);

通过这种方式利用addMacro替换成函数，执行时报错说sum(1,22) sum函数找不到，请问是什么问题？谢谢
