### ISSUE TITLE
符号保存会自动转换

### ISSUE THREAD

**Issue by maxiaoxian** [alibaba/QLExpress#41]
传入的[ - ]符号，输出会变成[ — ]

**Comment by baoxingjie** [comment]
不太明白意思

**Comment by maxiaoxian** [comment]
在脚本里面通过注入方式查询出来的的内容，如果是-，会自动转成中文—

**Comment by baoxingjie** [comment]
目前QLExpress的jar包里面没有类似的功能，你看看是不是系统的其他地方导致的，debug下系统代码看！
