### ISSUE TITLE
有没有规则检查工具

### ISSUE THREAD

**Issue by shibd** [alibaba/QLExpress#42]
你好，规则执行报错：
`程序错误，不满足语法规范，没有匹配到合适的语法,最大匹配致[0:0]`

报这种错感觉很难排查规则哪里写的不对。
各位在排查这种问题的方法是什么，有没有工具支持呢

**Comment by rongmin** [comment]
同问

**Comment by baoxingjie** [comment]
目前不是支持的很好，第一、要避免不要使用不支持的语法；第二、如果内容太长的话，建议分几句排查
