### ISSUE TITLE
关于QLExpress整合进spring的问题

### ISSUE THREAD

**Issue by cc19941109** [alibaba/QLExpress#5]
在用Qlexpress 表达式利用spring jpa 查询动态数据的时候，发现不能查询，感觉是repository没有注入的原因。
后面在网上找了篇文章  http://blog.csdn.net/express_wind/article/details/7468700 ，但是还是没有解决。
想问问如何解决这个问题

**Comment by baoxingjie** [comment]
感谢你的问题，感觉之前表述的有些不清楚，我重新写了一篇blog，http://blog.csdn.net/express_wind/article/details/78327650。
总体来说，很多spring的业务系统是非常适合和qlExpress集成的
https://github.com/alibaba/QLExpress/blob/master/src/test/java/com/ql/util/express/test/spring/SpringDemoTest.java
的如果还有疑问麻烦微信或者email给我哦
