### ISSUE TITLE
有个很想不明白的问题

### ISSUE THREAD

**Issue by objcoding** [alibaba/QLExpress#52]
如图：
![image](https://user-images.githubusercontent.com/24354760/53678674-75aa5380-3cfd-11e9-8964-3eddf2cb2790.png)

既然可以通过context传参，为什么还要在express那里填写参数，我觉得这样多次一举了，因为我现在遇到一个需求，我通过不定参数来做到表达式通用化的需求，但如果这样，就会破坏了通用性，而且，我没理解将function添加到runner里面有多方便，本来就是一个方法，直接调用不就得了，为什么调用时还要通过runner再一层包装呢？意义在哪里？

**Comment by baoxingjie** [comment]
QLExpress的宏和function主要是简化配置时候的理解成本，当然对于开发来说意义不大，但对系统业务配置人员。
你举得这个例子实际上主要是把method转化为为本地的function，而function是可以暴露成api列表给配置人员阅读的，而后面对应的method是系统级别的，需要制定class和methodName，不适合暴露给业务配置人员。

**Comment by baoxingjie** [comment]
另外你说的这个不希望通过参数传入，应该要使用宏定义

runner.addMacro("转化为大写"，“beanExample.upper(beanTest)”);
