### ISSUE TITLE
com.ql.util.express.ExpressRunner类线程安全么？

### ISSUE THREAD

**Issue by xingguang2013** [alibaba/QLExpress#53]
com.ql.util.express.ExpressRunner类线程安全么？

**Comment by welkinbai** [comment]
我自己测试不安全，行为不一致

**Comment by xingguang2013** [comment]
官方是不是已经不维护了？这么长时间都没有回复

**Comment by welkinbai** [comment]
> 官方是不是已经不维护了？这么长时间都没有回复

6小时前还commit代码呢，也许只是懒得理我们，哈哈

**Comment by xingguang2013** [comment]
@baoxingjie 能否说明下？

**Comment by baoxingjie** [comment]
不好意思，进入没有关注到issues
QLExpress是线程安全的，内部临时变量全部使用了threadLocal类型，可以放心使用
