### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by emmanual-liu** [alibaba/QLExpress#54]
6.7 - 100 > 39.6 ? 5 == 5 ? 4+5:6-1 : !(100%3-39.0<27) ? 8*2-199: 100%3
这个表达式在3.2.0和3.2.2都无法执行
![image](https://user-images.githubusercontent.com/9445276/56803542-7f5fbb80-6855-11e9-81f0-6a58e1824c63.png)

java本身或者其他表达式引擎都是正常的

**Comment by helpmeme** [comment]
留个微信？

**Comment by baoxingjie** [comment]
请多加一些括号，qlExpress的默认优先级并没有java这么多潜规则，只能保证简单的条理清晰的
