### ISSUE TITLE
区间表达式执行不支持

### ISSUE THREAD

**Issue by Viyond** [alibaba/QLExpress#55]
现在发现个问题，区间比较表达式，比如1<=a<=100，目前是不支持的，在执行的过程中会优先将1<=a得到的bool值和<=100做比较，这个时候就会抛出异常；

虽然使用1<=a && a<=100也可以兼容下，但是感觉这样还是不方便。请问下能否支持类似1<=a<=100这种表达式吗？

![image](https://user-images.githubusercontent.com/4710189/56860565-8f4cdc00-69ca-11e9-9629-84b45c157161.png)

**Comment by baoxingjie** [comment]
目前以java语法为标准
