### ISSUE TITLE
不知道是不是bug

### ISSUE THREAD

**Issue by wxb871127** [alibaba/QLExpress#57]
try {
            String expression = "tz >= 10 && tz <= 200";
            DefaultContext<String, Object> map = new DefaultContext<>();
            map.put("tz", "33");
            ExpressRunner runner = new ExpressRunner(false,true);
            Boolean result = (Boolean)runner.execute(expression, map, null, true, false);
            Log.e("result = ", result+"");
        } catch (Exception e) {
            e.printStackTrace();
        }
如上代码，运行结果是false 
把表达式换成String expression = "33 >= 10 && 33 <= 200"; 运行结果是true

**Comment by dragon0574** [comment]
个人算不上吧，我也碰到过，需要使用addFunctionOfClassMethod来讲变量转为数字类型Double或者Int类型来执行计算，不过还要看作者怎么说

**Comment by baoxingjie** [comment]
context 的value为Object，可以放入任何java对象类型，你这个明显是数字类型
在本例中：

map.put("tz", "33");

修改成 

map.put("tz", 33);
