### ISSUE TITLE
空置計算bug

### ISSUE THREAD

**Issue by 237158596** [alibaba/QLExpress#59]
ExpressRunner runner = new ExpressRunner(true,false);
		runner.addOperatorWithAlias("如果", "if",null);
		runner.addOperatorWithAlias("则", "then",null);
		runner.addOperatorWithAlias("否则", "else",null);

		String express = "如果  (语文+数学+英语>270) 则 {return 'good';} 否则 {return  'bad';}";
		DefaultContext<String, Object> context = new DefaultContext<String, Object>();

//		context.put("语文",1);
//		context.put("数学",2);
//		context.put("英语",3);
		List<String> errorList=new ArrayList<String>();
		Object r =runner.execute(express,context,errorList,false,false,null);

		System.out.println(r);   

不設置context,輸出  good

**Comment by baoxingjie** [comment]
这个是QLExpress弱类型语言处理上的兼容性造成的，目前的加号计算会把null默认当成"null"参与计算，所有最后变成了“nullnullnull”和270的比较，变成字符串的比较。对于你说的这种情况确实有一定的理解困难。
代码入口：
com.ql.util.express.OperatorOfNumber#add
com.ql.util.express.Operator#compareData
