### ISSUE TITLE
支持循环逻辑里面嵌套表达式

### ISSUE THREAD

**Issue by welkinbai** [alibaba/QLExpress#63]
请问怎样才能支持循环逻辑里面嵌套表达式。
比如有一个list，要针对list里面每个元素去执行一个表达式获得结果，仅当所有元素都符合表达式时整个表达式才返回true。

因为我要实现的是一个规则引擎，所以需要屏蔽掉for这种语法，只允许用户定义条件时输入xxx>xxx这样的操作符或者调用函数，不能有if 或者for这种分支循环。

我自己用新增function的方式实现，类似：EveryMatch(lists,element<3)
但是这个function里面需要执行element<3这句表达式很难实现，除非在function里面再创建ExpressRunner，把'element<3'当成string去执行，感觉不是很好，ExpressRunner的创建代价太大影响性能。

如果要能像函数式编程一样，表达式也能够作为参数传递就好了。或者有没有其他现有功能能够支持到？谢谢

**Comment by baoxingjie** [comment]
目前还没有打算支持这种表达式计算这种特性
