### ISSUE TITLE
addFunctionAndClassMethod 替换静态方法不正确

### ISSUE THREAD

**Issue by kylixs** [alibaba/QLExpress#64]
以下脚本没有替换掉System.exit方法
```
ExpressRunner runner = new ExpressRunner();
runner.addFunctionAndClassMethod("exit", System.class, myOperator);
DefaultContext<String, Object> context = new DefaultContext<String, Object>();
String express = "System.exit(1)";
Object r = runner.execute(express, context, null, true, false);
System.out.println(r);
```
但是修改为下面的方式则可以替换：
`runner.addFunctionAndClassMethod("exit", Class.class, myOperator);`
貌似 AppendingClassMethodManager.getAppendingClassMethod 方法判断有误，没有区分调用的是静态方法还是实例方法。
object.getClass() => System.class.getClass() = class java.lang.Class

**Comment by baoxingjie** [comment]
addFunctionAndClassMethod 是做映射的，并不是做替换的  "System.exit(1)";肯定不会发生改变

如果是想禁止使用这个api方法的话，请使用安全策略
https://github.com/alibaba/QLExpress/blob/master/src/test/java/com/ql/util/express/bugfix/InvokeSecurityRiskMethodsTest.java
