### ISSUE TITLE
支持设置脚本引擎可以访问的类方法的黑白名单

### ISSUE THREAD

**Issue by kylixs** [alibaba/QLExpress#65]
建议添加设置脚本引擎可以访问的类方法的黑白名单接口，目的是避免业务规则脚本错误调用某些类导致Java进程异常或者限制业务访问范围。

**Comment by welkinbai** [comment]
同意，强烈要求增加

**Comment by baoxingjie** [comment]
好的，在开发中

**Comment by baoxingjie** [comment]
https://github.com/alibaba/QLExpress/blob/master/VERSIONS.md
请试用下3.2.3版本
QLExpressRunStrategy.setForbiddenInvokeSecurityRiskMethods(true);
