### ISSUE TITLE
不支持添加无参的静态方法吗

### ISSUE THREAD

**Issue by kevin90828** [alibaba/QLExpress#66]
如题，添加无参的静态方式不报错，在execute的时候调用提示：
java.lang.Exception: 程序错误，不满足语法规范，没有匹配到合适的语法,最大匹配致[0:1]
	at com.ql.util.express.match.QLPattern.findMatchStatement(QLPattern.java:33)

**Comment by baoxingjie** [comment]
> 如题，添加无参的静态方式不报错，在execute的时候调用提示：
> java.lang.Exception: 程序错误，不满足语法规范，没有匹配到合适的语法,最大匹配致[0:1]
> at com.ql.util.express.match.QLPattern.findMatchStatement(QLPattern.java:33)

请把单元测试show一下
