### ISSUE TITLE
bug：如果String变量是长度为1的字符串，则无法渲染出实际值

### ISSUE THREAD

**Issue by mastery001** [alibaba/QLExpress#67]
代码如下
`
 ExpressRunner runner = new ExpressRunner();
DefaultContext<String , Object> context = new DefaultContext<>();
context.put("a" , 1);
Object value = runner.execute(”NewMap('a' : d2.a)“ , context , null , true , false);
`
上段代码的结果将会输出{a=null}

解决办法（个人看法）：
1. 将单字符为变量时，其类型判别为String，而非Character
2. 特殊兼容，在ExpressUtil第545行特殊兼容，当name为单字符时，转换为Character类型

【这里代码还未看全，所以暂时没考虑其他情况；暂不确定是否有问题】

**Comment by baoxingjie** [comment]
please ref:
https://github.com/alibaba/QLExpress/blob/master/VERSIONS.md#321%E7%89%88%E6%9C%AC2018-2-23
