### ISSUE TITLE
operator中调用原定义好的ExpressRunner会报空指针异常

### ISSUE THREAD

**Issue by hy-exe** [alibaba/QLExpress#69]
ExpressRunner expressRunner = new ExpressRunner();
        expressRunner.addFunction("$a", new Operator() {
            @Override
            public Object executeInner(Object[] list) throws Exception {
                return expressRunner.execute("return 1+1", new DefaultContext<>(), null, true, false);
            }
        });
        expressRunner.execute(" return $a()", new DefaultContext<>(), null, true, false);

**Comment by baoxingjie** [comment]
ExpressRunner 不能嵌套使用，这种情况需要拆成两个ExpressRunner 实例
