### ISSUE TITLE
使用qlExpress的引擎调用某个方法的时候，log无法打印。

### ISSUE THREAD

**Issue by linjian513** [alibaba/QLExpress#79]
场景：我又一个业务类，类中定义了各种方法，使用qlExpress的引擎调用该类的方法的时候，发现并没有任何日志输出，而代码里其他类进行调用的时候日志又是正常的。
       不知道大神们有无遇到这种问题？

**Comment by baoxingjie** [comment]
qlexpress只是简单的反射调用，建议你再这个方法内部调试下，应该就能找到不打印的原因，或者是没有执行到，或者是其他原因
