### ISSUE TITLE
Console.class.main方法执行不了，打开不了窗口

### ISSUE THREAD

**Issue by truechuan** [alibaba/QLExpress#8]
如题，对比了阿里云上面的早起代码，猜测是缺少这部分代码http://code.taobao.org/p/QLExpress/src/branches/3.0.3/src/main/resources/com/ql/util/express/console/

**Comment by baoxingjie** [comment]
谢谢你的提醒，因为很早之前这个功能只是作为一个测试功能玩一下，后来工程调整中为了降低jar的大小删除了，目前已经恢复在test目录中。
