### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by gjsuper** [alibaba/QLExpress#81]
1.看了下代码里指令缓存貌似没有淘汰机制，清除缓存只能调用clearExpressCache方法或者重启机器，以后是否会有指令缓存的淘汰策略
2.对象池的大小是30个，后续能否可以做成一个可配置的参数

**Comment by baoxingjie** [comment]
1、可以通过com.ql.util.express.ExpressRunner#parseInstructionSet自己封装，结合google Guava Cache等
2、可以增加后续配置
