### ISSUE TITLE
关于表自定义函数中再使用表达式的求助

### ISSUE THREAD

**Issue by sluk3r** [alibaba/QLExpress#82]
Hi， 在使用QLExpress的过程中， 碰到这么一个问题， 想在自定义函数入参中，再使用子表达式， 一时没有较好的解决方式， 于是利用此Issue请想大家帮看下。 

表达式如下： 
order.orderType in (0,112,21) && skuPropertySatisfied(skuList, "categoryId=3&&price=100")

此表达式的业务规则是：
1. 如果订单类型0或112或21
2. 此订单下某个商品的品类Id是3且此商品对应的价格是100

如果上面的两个条件都满足的话， 刚执行一段业务逻辑。 

上面表达中，skuPropertySatisfied是自定义的函数， 可以通过com.ql.util.express.ExpressRunner#addFunctionOfClassMethod(java.lang.String, java.lang.String, java.lang.String, java.lang.String[], java.lang.String)方法注册进来到ExpressRunner中。 

现在这样的注册机制下，自定义函数的skuPropertySatisfied入参“categoryId=3&&price=100”， 不能直接被ExpressRunner执行。 

请大家帮看下， 这样的合适场景，咱QLExpress怎么支持下？

**Comment by welkinbai** [comment]
我也想知道

**Comment by baoxingjie** [comment]
view the example 
https://github.com/alibaba/QLExpress/blob/master/src/test/java/com/ql/util/express/bugfix/RecursivelyRunnerTest.java

**Comment by fq1798** [comment]
终于被我尝试出来了。

1，写这个类： GetStockCode extends OperatorBase {
其实 就是方法：  getStockCode 方法；这个方法第二个参数是一个字符串；这个字符串是一个表达式，
2，此时可以使用如下代码进行处理，解决。

  `InstructionSet instructionSet = parent.getExpressRunner().parseInstructionSet(calc);
        RunEnvironment environment = OperateDataCacheManager.fetRunEnvironment(instructionSet, parent, false);

        Object result = null;
        CallResult callResult = instructionSet.excute(environment, parent, null, true, null);
        if (callResult.isExit() == true) {
            result = callResult.getReturnValue();
        }

if(result == null) {
            return OperateDataCacheManager.fetchOperateData(null, null);
        } else {
            return OperateDataCacheManager.fetchOperateData(result, result.getClass());
        }`
