### ISSUE TITLE
比较null返回false有问题

### ISSUE THREAD

**Issue by zengjianfei** [alibaba/QLExpress#86]
QLExpressRunStrategy.setCompareNullLessMoreAsFalse(true); 这个设置无效。版本3.2.4

![image](https://user-images.githubusercontent.com/19281456/70403427-bcd62980-1a71-11ea-91c2-0dac6093c11d.png)

**Comment by baoxingjie** [comment]
thank you for your question,please focus on 
3.2.4版本[2019-12-6]
(1)增加null的数字比较方案"1>null"":NullCompareTest
https://github.com/alibaba/QLExpress/blob/master/VERSIONS.md

**Comment by baoxingjie** [comment]
thank you for your question,please focus on 
3.2.4版本[2019-12-6]
(1)增加null的数字比较方案"1>null"":NullCompareTest
https://github.com/alibaba/QLExpress/blob/master/VERSIONS.md

**Comment by zengjianfei** [comment]
这种没有问题
![image](https://user-images.githubusercontent.com/19281456/70409420-aeded380-1a86-11ea-8cec-cfcfcf9c5342.png)

有问题的是这种情况
![image](https://user-images.githubusercontent.com/19281456/70409475-d7ff6400-1a86-11ea-9c6a-6336000bc487.png)

**Comment by zengjianfei** [comment]
![image](https://user-images.githubusercontent.com/19281456/70409505-f1081500-1a86-11ea-8569-aa4e09c0fdaf.png)
上面这种情况才有问题有问题
下面这种没有问题
![image](https://user-images.githubusercontent.com/19281456/70409573-26acfe00-1a87-11ea-992e-8d6dacf4bf0f.png)
