### ISSUE TITLE
请确认是否是一个Bug?

### ISSUE THREAD

**Issue by Hong-Chao-Tan** [alibaba/QLExpress#89]
只是初始化一个DefaultContext对象，并没有put值，执行以下代码回返回1（如果表达做小比较，则返回0），变量没有赋值就能相加并能做大小比较，这算个Bug吗？
           `ExpressRunner runner = new ExpressRunner();
            DefaultContext<String, Object> context = new DefaultContext<String, Object>();
            runner.addOperatorWithAlias("如果", "if",null);
            runner.addOperatorWithAlias("则", "then",null);
            runner.addOperatorWithAlias("否则", "else",null);
            String exp = "如果  (语文+英语>270) 则 {return 1;} 否则 {return 0;}";
            Object r = runner.execute(exp,context,null,false,false,null);
            System.out.println(r);`

初步分析：OperatorOfNumber中的add方法实现逻辑是当两个null对象进行相加操作返回的是两个null字符串的拼接结果（字符串拼接最好用StringBuilder），最后在OperatorEqualsLessMore中的executeInner方法变成"nullnull"和数字的字符串进行作大小比较，结果显而易见。

**Comment by baoxingjie** [comment]
如果为null，在QLExpress是会作为字符串处理，因为脚本语言一般的设计理念是旨在增强语法的兼容性。如果你希望可以验证判断报错，可能要自己去重新实现下OperatorOfNumber
