### ISSUE TITLE
Context中没有对应的key时条件判断识别问题

### ISSUE THREAD

**Issue by ghostPM** [alibaba/QLExpress#92]
以下代码返回的是true，但province和guangdong在上下文中均没有设置，按照语义应该返回false
        ExpressRunner runner = new ExpressRunner();
        DefaultContext<String, Object> context = new DefaultContext<String, Object>();
        context.put("a", 123);
        String express = "province==guangdong";
        Object r = runner.execute(express, context, null, true, false);
        System.out.println(r);

当guangdong加上双引号时，结果正常
        ExpressRunner runner = new ExpressRunner();
        DefaultContext<String, Object> context = new DefaultContext<String, Object>();
        context.put("a", 123);
        String express = "province==\"guangdong\"";
        Object r = runner.execute(express, context, null, true, false);
        System.out.println(r);

或者上下文增加province时候，结果正常
        ExpressRunner runner = new ExpressRunner();
        DefaultContext<String, Object> context = new DefaultContext<String, Object>();
        context.put("province", "guangxi");
        String express = "province==guangdong";
        Object r = runner.execute(express, context, null, true, false);
        System.out.println(r);

**Comment by baoxingjie** [comment]
guangdong 是变量，如果context里面没有，会是null
 “guangdong” 是string常量
