### ISSUE TITLE
README.md文档中 operator的addFunction操作不正确

### ISSUE THREAD

**Issue by tzh921129** [alibaba/QLExpress#95]
ExpressRunner runner = new ExpressRunner();
DefaultContext<String, Object> context = new DefaultContext<String, Object>();
runner.addFunction("join",new JoinOperator());
Object r = runner.execute("join(1,2,3)", context, null, false, false);
System.out.println(r);

理论输出是[1,2,3] 实际输出是[1,2]

**Comment by DQinYuan** [comment]
文档中的例子是 addOperator，你却把它 addFunction ....

**Comment by tzh921129** [comment]
后来试了下，JoinOperator用下面这个的addFunction也是可以的
public class JoinOperator extends Operator {
    public Object executeInner(Object[] list) throws Exception {
        java.util.List result = new java.util.ArrayList();
        Object opdata1 = list[0];
        if(opdata1 instanceof java.util.List){
            result.addAll((java.util.List)opdata1);
        }else{
            result.add(opdata1);
        }
        for(int i=1;i<list.length;i++){
            result.add(list[i]);
        }
        return result;
    }
}

**Comment by tzh921129** [comment]
1. 个人的operator写的不正确，所以关闭issure
