### ISSUE TITLE
这个工程持续维护么

### ISSUE THREAD

**Issue by geektcp** [alibaba/QLExpress#96]
如题

**Comment by kubilee** [comment]
我也想知道

**Comment by fangjiaxiaobai** [comment]
+1

**Comment by DQinYuan** [comment]
+1

**Comment by hiliushuo** [comment]
应该不会维护了，作者已经离开阿里了

**Comment by baoxingjie** [comment]
确实已经1年多没有啥更新了，近期会针对性的解决一些问题

**Comment by geektcp** [comment]
> 应该不会维护了，作者已经离开阿里了

还是饭碗要紧，开源只是理想主义。不过我现在正好在开源一个项目 https://github.com/geektcp/garden.git  QQ群：832287647

**Comment by geektcp** [comment]
> 应该不会维护了，作者已经离开阿里了

还是饭碗要紧，开源只是理想主义。不过我现在正好在开源一个项目 https://github.com/geektcp/garden.git  QQ群：832287647
